### ISSUE TITLE
实现和论文有差异

### ISSUE THREAD

**Issue by whyandbecause** [BiQiWHU/CMFormer#1]
您好，看了您这篇论文的工作，我发现论文框架图中下采样是在masked attention和self-attention**之前**的，但是代码里好像下采样操作是在masked attention和self-attention**之间**的，也就是下采样后的特征只经过了self-attention，没有经过masked attention。所以想咨询下，是以哪个为准？谢谢！

**Comment by BiQiWHU** [comment]
请以代码为准，本文mask attention的框架依照原Mask2Former。祝好！
