### ISSUE TITLE
Request for the pretrained model 

### ISSUE THREAD

**Issue by gaozhitong** [BiQiWHU/CMFormer#3]
Thanks for your interesting work! I want to evaluate the model's performance on another benchmark. For a fair comparison, could you please share your pretrained model checkpoints? Thanks in advance!

**Comment by BiQiWHU** [comment]
Thanks for your interest to your work! Please refer to the attach file for our pre-trained model on CityScapes.

https://drive.google.com/file/d/15vQm8hWQe7wyiI9q3t13-yBmcX3EZHrn/view?usp=drive_link

**Comment by whyandbecause** [comment]
Hi, could you aslo please share your pretrained model checkpoints on GTAV? Thanks a lot.

**Comment by BiQiWHU** [comment]
For GTA pre-trained model, could you download it from Baidu Cloud Disk?

链接：https://pan.baidu.com/s/1EU4WranLCy34kihB63ksiQ?pwd=e0bv 
提取码：e0bv 
--来自百度网盘超级会员V5的分享
