### ISSUE TITLE
Request for the pretrained model trained on GTAV

### ISSUE THREAD

**Issue by tpy001** [BiQiWHU/CMFormer#4]
Thanks for your interesting work! 
I want to evaluate the model's performance on another benchmark. 
For a fair comparison, could you please share your pretrained checkpoints on GTAV? 
Thanks in advance!

**Comment by BiQiWHU** [comment]
Thanks for your interest in our work!

Could you use Baidu Cloud Disk to download files?

If so, you can download through this link:

链接：https://pan.baidu.com/s/1EU4WranLCy34kihB63ksiQ?pwd=e0bv 
提取码：e0bv 
--来自百度网盘超级会员V5的分享

Thanks in advance!

**Comment by whyandbecause** [comment]
您好，请问可以提供谷歌网盘的链接吗？百度网盘下载速度太慢了。谢谢！

**Comment by tpy001** [comment]
Hi, I successfully reproduced the results on GTAV -> Cityscapes. However, I noticed that the model's backbone is Swin-Base. Why not use Swin Large? I believe it might further improve performance.

**Comment by BiQiWHU** [comment]
Hi there, thanks for your interest on this project!

The representation learning technique develops really fast. By the time we study this project, existing domain generalized semantic segmentation methods only use ResNet-50 or ResNet-101 based backbone. So at that time we mostly used Swin-Base.

But yes, if you use Swin-Large or foundation model based encoder, of course it will have a better generalization ablity.
